-- ============================================================================
-- ShopFlow MVP - Initial Schema Migration
-- Date: 2025-11-09
-- Version: 1.0.0
-- Description: Schema inicial do banco de dados ShopFlow MVP
-- ============================================================================

-- IMPORTANTE: Este é o estado inicial do banco após setup
-- Aplicar apenas em bancos novos ou para documentação

BEGIN;

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

-- UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Cryptographic functions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- TABLE: camera_events
-- ============================================================================
-- Armazena eventos processados pela câmera com detecções de IA
-- Cada linha representa um frame processado com suas métricas

CREATE TABLE IF NOT EXISTS public.camera_events (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Timestamp e identificação
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    camera_id TEXT NOT NULL DEFAULT 'camera1',
    
    -- Métricas de detecção (valores calculados pela IA)
    total_people INTEGER NOT NULL DEFAULT 0,
        -- Total de pessoas detectadas no frame
    
    employees_count INTEGER NOT NULL DEFAULT 0,
        -- Funcionários identificados via reconhecimento facial
    
    groups_count INTEGER NOT NULL DEFAULT 0,
        -- Número de grupos detectados (clustering DBSCAN)
    
    potential_customers INTEGER NOT NULL DEFAULT 0,
        -- Clientes potenciais calculados (total - employees - ajuste grupos)
    
    groups_detail JSONB,
        -- Array JSON com detalhes de cada grupo:
        -- [{"group_id": 1, "size": 3, "bbox": [x, y, w, h]}, ...]
    
    -- Performance metrics
    processing_time_ms INTEGER,
        -- Tempo de processamento do frame (milissegundos)
    
    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comentários explicativos
COMMENT ON TABLE public.camera_events IS 'Eventos processados pela câmera com detecções de IA';
COMMENT ON COLUMN public.camera_events.total_people IS 'Total de pessoas detectadas no frame';
COMMENT ON COLUMN public.camera_events.employees_count IS 'Funcionários identificados';
COMMENT ON COLUMN public.camera_events.groups_count IS 'Número de grupos detectados';
COMMENT ON COLUMN public.camera_events.potential_customers IS 'Clientes potenciais calculados';
COMMENT ON COLUMN public.camera_events.groups_detail IS 'Array JSON com detalhes de cada grupo';

-- Índices para queries comuns (removidos índices não utilizados)
-- CREATE INDEX IF NOT EXISTS idx_camera_events_timestamp ON public.camera_events(timestamp);
-- CREATE INDEX IF NOT EXISTS idx_camera_events_camera_time ON public.camera_events(camera_id, timestamp);
-- CREATE INDEX IF NOT EXISTS idx_camera_events_created ON public.camera_events(created_at);
-- Nota: Índices removidos após análise - não eram utilizados

-- ============================================================================
-- TABLE: employees
-- ============================================================================
-- Cadastro de funcionários para reconhecimento facial (LGPD compliant)
-- Armazena apenas embeddings faciais, não imagens

CREATE TABLE IF NOT EXISTS public.employees (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Informações básicas
    name TEXT NOT NULL,
    employee_id TEXT UNIQUE,
        -- ID do funcionário (CPF, matrícula, etc)
    
    -- Organização
    department TEXT,
        -- Departamento/setor
    position TEXT,
        -- Cargo
    
    -- Reconhecimento Facial (LGPD Compliant)
    embedding FLOAT8[] NOT NULL,
        -- Embedding facial (128 dimensões) para reconhecimento
        -- IMPORTANTE: NÃO armazenamos a imagem original
        -- Apenas o vetor matemático para comparação
    
    -- Status
    status TEXT NOT NULL DEFAULT 'active',
        -- Status: 'active' ou 'inactive'
    
    -- Audit timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comentários explicativos
COMMENT ON TABLE public.employees IS 'Funcionários cadastrados para reconhecimento facial';
COMMENT ON COLUMN public.employees.embedding IS 'Embedding facial (128 dimensões) para reconhecimento';
COMMENT ON COLUMN public.employees.status IS 'Status: active ou inactive';

-- Índices para queries comuns (removidos índices não utilizados)
-- CREATE INDEX IF NOT EXISTS idx_employees_status ON public.employees(status);
-- CREATE INDEX IF NOT EXISTS idx_employees_created ON public.employees(created_at);
-- Nota: Índices removidos após análise - não eram utilizados

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Habilitar RLS nas tabelas
ALTER TABLE public.camera_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Política para camera_events
-- Permite acesso completo apenas para service_role (backend)
DROP POLICY IF EXISTS "service_role_access" ON public.camera_events;
CREATE POLICY "service_role_access" ON public.camera_events
    FOR ALL
    TO public
    USING ((SELECT auth.role()) = 'service_role');

-- Política para employees
-- Permite acesso completo apenas para service_role (backend)
DROP POLICY IF EXISTS "service_role_access" ON public.employees;
CREATE POLICY "service_role_access" ON public.employees
    FOR ALL
    TO public
    USING ((SELECT auth.role()) = 'service_role');

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar updated_at em employees
DROP TRIGGER IF EXISTS update_employees_updated_at ON public.employees;
CREATE TRIGGER update_employees_updated_at
    BEFORE UPDATE ON public.employees
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- GRANTS
-- ============================================================================

-- Garantir acesso ao service_role
GRANT ALL ON public.camera_events TO service_role;
GRANT ALL ON public.employees TO service_role;
GRANT USAGE ON SEQUENCE public.camera_events_id_seq TO service_role;

-- ============================================================================
-- VALIDATION
-- ============================================================================

-- Verificar tabelas criadas
DO $$
BEGIN
    ASSERT (SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name IN ('camera_events', 'employees')) = 2,
           'Tables not created correctly';
    
    RAISE NOTICE '✅ Schema migration completed successfully';
    RAISE NOTICE '   - camera_events table created';
    RAISE NOTICE '   - employees table created';
    RAISE NOTICE '   - RLS policies applied';
    RAISE NOTICE '   - Triggers configured';
END $$;

COMMIT;

-- ============================================================================
-- NEXT STEPS
-- ============================================================================
-- 1. Verificar estrutura: \dt public.*
-- 2. Verificar políticas: SELECT * FROM pg_policies WHERE schemaname = 'public';
-- 3. Testar inserção de dados de teste
-- 4. Executar linter: supabase db lint
-- ============================================================================